// <auto-generated />
using System;
using Innowise.Clinic.Profiles.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innowise.Clinic.Profiles.Persistence.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    [Migration("20230214065616_SeedDoctorStatuses")]
    partial class SeedDoctorStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CareerStartYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoctorId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StatusId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.DoctorStatus", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = new Guid("e8dfe97a-1c89-45ff-b08c-a97f6edc5e41"),
                            Description = "At work",
                            Name = "At work"
                        },
                        new
                        {
                            StatusId = new Guid("724eac90-dee0-454e-bdc5-10742042bbdd"),
                            Description = "On vacation",
                            Name = "On vacation"
                        },
                        new
                        {
                            StatusId = new Guid("7be6ae9f-1534-416c-b420-c2c191f7b3fc"),
                            Description = "Sick Day",
                            Name = "Sick Day"
                        },
                        new
                        {
                            StatusId = new Guid("53bc1111-9b82-4e0a-9c79-4132e7d3e472"),
                            Description = "Sick Leave",
                            Name = "Sick Leave"
                        },
                        new
                        {
                            StatusId = new Guid("2270714a-25a4-467b-b07a-3ce15b4fa035"),
                            Description = "Self-isolation",
                            Name = "Self-isolation"
                        },
                        new
                        {
                            StatusId = new Guid("5a2466e3-ad9d-4454-86f6-ae6e63183116"),
                            Description = "Leave without pay",
                            Name = "Leave without pay"
                        },
                        new
                        {
                            StatusId = new Guid("27fddac5-d7cc-41d4-b22d-ff41b98a09d7"),
                            Description = "Inactive",
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("PersonId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Receptionist", b =>
                {
                    b.Property<Guid>("ReceptionistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReceptionistId");

                    b.HasIndex("PersonId");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Doctor", b =>
                {
                    b.HasOne("Innowise.Clinic.Profiles.Persistence.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innowise.Clinic.Profiles.Persistence.Models.DoctorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Patient", b =>
                {
                    b.HasOne("Innowise.Clinic.Profiles.Persistence.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Innowise.Clinic.Profiles.Persistence.Models.Receptionist", b =>
                {
                    b.HasOne("Innowise.Clinic.Profiles.Persistence.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
